# Generated by Django 6.0.2 on 2026-03-07 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_status_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Wallets & Bags', 'Wallets & Bags'), ('Keys', 'Keys'), ('Clothing', 'Clothing'), ('Jewelry', 'Jewelry'), ('Documents', 'Documents'), ('Pets', 'Pets'), ('Sports', 'Sports'), ('Other', 'Other')], db_index=True, max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('date_lost', models.DateField()),
                ('description', models.TextField()),
                ('location_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('time_lost', models.TimeField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('distinguishing_features', models.TextField(blank=True, null=True)),
                ('reward', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('matched', 'Matched'), ('claimed', 'Claimed'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost Report',
                'verbose_name_plural': 'Lost Reports',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.lostreport')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
