# Generated by Django 6.0.2 on 2026-03-08 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lostreport_reportimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostreport',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RenameField(
            model_name='lostreport',
            old_name='date_lost',
            new_name='date_event',
        ),
        migrations.RenameField(
            model_name='lostreport',
            old_name='time_lost',
            new_name='time_event',
        ),
        migrations.AddField(
            model_name='lostreport',
            name='found_stored_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='matched_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to='api.lostreport'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='report_type',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], db_index=True, default='lost', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='api.lostreport')),
            ],
            options={
                'verbose_name': 'Claim Request',
                'verbose_name_plural': 'Claim Requests',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('report_received', 'Report Received'), ('under_review', 'Under Review'), ('matched', 'Matched'), ('claim_received', 'Claim Received'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('report_closed', 'Report Closed'), ('report_rejected', 'Report Rejected')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.claimrequest')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.lostreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('score_breakdown', models.JSONField(default=dict)),
                ('confidence', models.CharField(default='low', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_report', models.ForeignKey(limit_choices_to={'report_type': 'found'}, on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions_as_found', to='api.lostreport')),
                ('lost_report', models.ForeignKey(limit_choices_to={'report_type': 'lost'}, on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions_as_lost', to='api.lostreport')),
            ],
            options={
                'verbose_name': 'Match Suggestion',
                'verbose_name_plural': 'Match Suggestions',
                'ordering': ['-score'],
                'unique_together': {('lost_report', 'found_report')},
            },
        ),
    ]
