# Generated by Django 6.0.2 on 2026-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lostreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('report_received', 'Report Received'), ('under_review', 'Under Review'), ('matched', 'Matched'), ('claim_received', 'Claim Received'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('report_closed', 'Report Closed'), ('report_rejected', 'Report Rejected'), ('new_report', 'New Report Submitted'), ('new_claim', 'New Claim Submitted')], db_index=True, max_length=20),
        ),
    ]
