# Generated by Django 6.0.2 on 2026-03-12 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_notif_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registered'), ('password_change', 'Password Changed'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('report_closed', 'Report Closed'), ('claim_submitted', 'Claim Submitted'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('match_confirmed', 'Match Confirmed'), ('match_dismissed', 'Match Dismissed'), ('match_run', 'AI Match Run'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_deleted', 'User Deleted'), ('role_changed', 'Role Changed')], db_index=True, max_length=40)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], default='user', max_length=10)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.claimrequest')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lostreport')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
